# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b77015894334649ae8e4cda9ce734b34a273a3e8be3ccfbc34ea2c3f94dc816127824e040007a6a74baed7f413e02cefde29a0655e7eda37c46ce06a645ec2cf

test:
  secret_key_base: 9030b362d394bdbb148d65504055fd327edc32e01d016c0df25b7c78641df5ceaadd72f3923d8395be7fc851b83b3d379c009f9fea5a3a3ab6a49d62a048e7b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
